- name: youtube
  host: "https://www.youtube.com" 
  match:
    pattern: "^/watch\\?v=([a-zA-Z0-9\\_-]{11})"
    matchnum: 1
    regexp: null
  target: 
    query: a
    attr: href
    current: 
      - filter: ".yt-ui-ellipsis.yt-ui-ellipsis-2.yt-uix-sessionlink.spf-link"
        action: css
        args:
          color: red
    parents: []
    children: 
      - query: "span.title"
        action: css
        args:
          color: red
      - query: "span.yt-thumb-simple"
        action: append
        args: "<span style='color: white; background-color: red; font-size: 12px; height: 15px; line-height: 15px; position: absolute; left: 2px; bottom: 2px; padding: 0 4px 0 4px; opacity: 0.7;'>File Exists</span>"
  file:
    directory: ""
    pattern: "^([a-zA-Z0-9\\_-]{11})"
    matchnum: 1
